[package]
name = "bundles-indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
shuttle-axum = "0.50.0"
shuttle-runtime = "0.50.0"
axum = "0.7.4"
tokio = {version = "1.43.0", features = ["full"]}
bundler = {git = "https://github.com/weaveVM/bundler", branch = "main"}
anyhow = "1.0.96"
